

const dogList=[
    {
      "id": 4709,
      "ficha": "04423",
      "raza": "AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2010-09-07T00:00:00",
      "edad": "Mayor (5 años)",
      "tamagno": "Grande (26-44 kg)",
      "observaciones": "es necesaria licencia y seguro. \r\n\r\nES muy  bueno y jugueton con la gente, muy activo.\r\nPero no se lleva bien con otros perros y perras. \r\nIdeal para una casa sin perros\r\nEstá esterilizado\r\nSE MERECE UN HOGAR!!\r\nTerry actualmente no se encuentra en el centro por lo que si quieres adoptarlo debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/terry2.jpg",
      "nombre": "Terry (G)",
      "especie": "Canina",
      "color": "Blanco y Atigrado",
      "peligroso": true,
      "microchip": "NO/941000017300165",
      "cartilla": "NO/ES02178853",
      "rabia": false,
      "fechaRabia": "2014-12-31T00:00:00",
      "esterilizado": true,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "27/12/14 rabia\r\n13/3/15 esterilizado cmpa zgz\r\n31/12/15 rabia\r\n18/01/2016 Llevado a guardería.\r\n13/02/19 leishmania negativo calva en cabeza",
      "fechaIngreso": "2014-09-07T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": true,
      "horaUrgencias": "16:14",
      "numPolicia": "1272 (Llamada) y 924 + 1521(+-) (Presente)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "C/ Rioja nº14",
      "disponible": "1",
      "tasa": "Ent: Encontrado+ sal: ",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 6125,
      "ficha": "05482",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Hembra",
      "fechaNac": "2015-08-01T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Lola actualmente no se encuentra en el centro por lo que si quieres adoptarla debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/LOLA.jpg",
      "nombre": "Lola (G)",
      "especie": "Canina",
      "color": "chocolate pecho blanco",
      "peligroso": true,
      "microchip": "NO/941000018747690",
      "cartilla": "NO/ES020209839",
      "rabia": false,
      "fechaRabia": "2016-01-28T00:00:00",
      "esterilizado": false,
      "perdido": false,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "está en guardería de un ciudadano que se encuentra en el Refugio\r\nEl ciudadano debe entrar tres meses a prisión. La oficina decide mantener al animal hasta que legalice su situación\r\n15/11/2016 llevada a al guardería.",
      "fechaIngreso": "2016-01-14T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": false,
      "nombreSolicitante": "Javier Miguel",
      "apellidosSolicitante": "Remacha Esteban",
      "dniSolicitante": "72883043E",
      "telefonoSolicitante": "622525161",
      "domicilioSolicitante": "Albergue",
      "disponible": "1",
      "tasa": "Ent:  otra",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 6267,
      "ficha": "05944",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2015-03-26T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Ricardo actualmente no se encuentra en el centro por lo que si quieres adoptarlo debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/05944 Ricardo.jpg",
      "nombre": "Ricardo (G)",
      "especie": "Canina",
      "color": "negro y blanco",
      "peligroso": true,
      "microchip": "NO/941000019020741",
      "cartilla": "NO/ES020214520",
      "rabia": false,
      "fechaRabia": "2016-06-21T00:00:00",
      "esterilizado": true,
      "perdido": false,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "prazitel scalibor\r\ndhppi+l 5/4/16\r\n28/4/16 tto vómitos ranitidina y cerenia.\r\n29/4/16 vigilar, tiene mocos\r\n21/6/16 rabia\r\n15/11/2016 Llevado a guarderia\r\n12/16 esterilizado CEA\r\n13/02/19 leishmania negativo",
      "fechaIngreso": "2016-03-26T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": false,
      "numPolicia": "1261(ll) 1153, 1421(pr)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "Vistabella 259 Juan de Lanuza",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 5972,
      "ficha": "05662",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2014-11-08T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "necesaria licencia y seguro de perro potencialmente peligroso para adoptar a Golf.\r\nGolf actualmente no se encuentra en el centro por lo que si quieres adoptarlo debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/05662 Golf.jpg",
      "nombre": "Golf (G)",
      "especie": "Canina",
      "color": "marron y blanco",
      "peligroso": false,
      "microchip": "NO/941000018459836",
      "cartilla": "NO/ES020200849",
      "rabia": false,
      "fechaRabia": "2015-11-16T00:00:00",
      "esterilizado": false,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "prazitel\r\nchip rabia pas en cmpa\r\n15/11/2016 llevado a guardería",
      "fechaIngreso": "2015-11-08T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": true,
      "horaUrgencias": "11:30",
      "numPolicia": "1276(ll) 1455, 1777(pr)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "Mercadona de Avda. Cataluña",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 5295,
      "ficha": "04982",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER CON BOXER",
      "sexo": "Macho",
      "fechaNac": "2013-04-05T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Fue recogido vagando por el campo.\r\n\r\nLleva dos años en el centro\r\n\r\nEs  Jugueton y sociable con gente, pero no se lleva muy bien con otros machos\r\n\r\nNecesita un buen hogar, ya se lo merece.\r\n\r\nWho actualmente no se encuentra en el centro por lo que si quieres adoptarlo debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/04982 Who.jpg",
      "nombre": "Who (G)",
      "especie": "Canina",
      "color": "negro y blanco",
      "peligroso": false,
      "microchip": "NO/941000017677451",
      "cartilla": "NO/ES020187100",
      "rabia": false,
      "fechaRabia": "2015-05-16T00:00:00",
      "esterilizado": false,
      "perdido": true,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "con collar\r\nchip, pas y rabia an cmpa\r\n13/11/16 se modifica raza, es ppp\r\n21/6/16 rabia\r\n23/6/16 DHPPI+l\r\n14/11/2016 Llevado a guardería. ",
      "fechaIngreso": "2015-04-05T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": true,
      "horaUrgencias": "23:00",
      "numPolicia": "734",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "pza. olleta 18",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 4931,
      "ficha": "04631",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2013-06-17T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Es muy bueno, se lleva muy bien con las personas, pero necesita un hogar que no tenga otros perros, ya que no se lleva muy bien con sus congéneres, \r\n\r\nEstá esterilizado.\r\n\r\n\r\nnecesaria licencia y seguro de perros potencialmente peligrososo\r\nESTÁ ESTERILIZADO\r\nBrown actualmente no se encuentra en el centro por lo que si quieres adoptarlo debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/braum2.jpg",
      "nombre": "BROWN (G)",
      "especie": "Canina",
      "color": "MARRON",
      "chenil": "C-",
      "peligroso": true,
      "microchip": "NO/941000017300320",
      "cartilla": "NO/es020189733",
      "rabia": false,
      "fechaRabia": "2015-04-29T00:00:00",
      "esterilizado": true,
      "perdido": true,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "tratado con ab por haber sido mordido. no tiene buen aspecto\r\nestá mejor.da problemas con otros perros pero bueno con personas.\r\nchip rabia pas en cmpa\r\n5/2015 ESTERILIZADO EN CMPA\r\n07/09/2016 Llevado a guardería.\r\n13/02/19 leishmania negativo ",
      "fechaIngreso": "2014-11-12T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": false,
      "numPolicia": "1515(LL) 1846(PR)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "C/ Mariano Gracia nº15",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 5249,
      "ficha": "04945",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Hembra",
      "fechaNac": "2014-05-26T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Necesita licencia de perro potencialmente peligroso y seguro de responsabilidad civil\r\n\r\nEntró al centro con diez meses. Durante largo tiempo convivió sin proplemas con otra ppp del Centro, al principio todo fue bien, pero hace poco susgieron problemas entre ellas.\r\nActualmente no se encuentra en el centro por lo que si quieres adoptarla debes contactar con nosotros en 976836554.\r\nMaribel está vacunada y esterilizada, ahora necesita un buen hogar\r\nRecogida abandonada, vagando por el campo.  La pobre tan joven conoce perfectamente el maltrato animal.\r\n",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/MARIBEL11.jpg",
      "nombre": "Maribel (G)",
      "especie": "Canina",
      "color": "Blanco y negro",
      "chenil": "entrada",
      "peligroso": true,
      "microchip": "NO/941000017300182",
      "cartilla": "NO/ES020189732",
      "rabia": false,
      "fechaRabia": "2015-04-28T00:00:00",
      "esterilizado": true,
      "perdido": true,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "recogida por pablo en camino cabañera\r\nchip rabia pas en cmpa zgz\r\n11/4/16 dhppil\r\n21/6/16 rabia\r\n11/16 desp int y ext\r\n11/16 oht hvuz\r\n16/11/16 envio a guarderia",
      "fechaIngreso": "2015-03-26T00:00:00",
      "formaEntrada": "Otros",
      "entrada": "Encontrado",
      "urgencias": false,
      "nombreSolicitante": "cmpa",
      "domicilioSolicitante": "camino cabañera km 1,2",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 4478,
      "ficha": "04189",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2012-07-08T00:00:00",
      "tamagno": "Grande (26-44 kg)",
      "observaciones": "Es muy cariñoso y tranquilo\r\n\r\nSE MERECE UN BUEN HOGAR, EL SABE BIEN LO QUE ES EL MALTRATO Y POSTERIORMENTE EL ABANDONO.\r\nEn el Centro ha encontrado cariño y un hogar, pero se merece una casita, donde nunca nadie más lo maltrate.\r\nAsidon actualmente no se encuentra en el centro por lo que si quieres adoptarlo debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/ASIDON11.jpg",
      "nombre": "ASIDON ",
      "especie": "Canina",
      "color": "ATIGRADO",
      "peligroso": true,
      "microchip": "941000016656431 ",
      "cartilla": "ES020163332",
      "rabia": true,
      "fechaRabia": "2014-09-16T00:00:00",
      "esterilizado": true,
      "perdido": false,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "ENTREGADO POR SEPRONA. LO TENIAN UNOS INDIVIDUOS DE RAZA GITANA ATADO A UNA CADENA\r\n7/7/14  CHIP: 941000016656431  PAS: ES 020163332\r\n16/09/2014 VR\r\nleishmania tto alopurinol + enalapril(1m) mejora mucho\r\nmantengo alopurinol descanso 27/07/15 al 27/08/15\r\nalopurinol 1 compr cada dia tres meses y uno de descanso\r\n11/4/16 dhppi+l\r\n31/12/16 rabia\r\n03/05/2017 se lleva a guardería.\r\n13/02/19 leishmania negativo",
      "fechaIngreso": "2014-07-03T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Otra",
      "urgencias": false,
      "numPolicia": "SARGENTO EGIDO(LL) P29313",
      "nombreSolicitante": "SEPRONA",
      "domicilioSolicitante": "LA TORRE ASIDON 214",
      "disponible": "1",
      "tasa": "ENT: OTRO",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 5753,
      "ficha": "05441",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Hembra",
      "fechaNac": "2015-02-22T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Lleva ya 3 años en el centro, se merece un hogar. Esta perrita se lleva muy bien con las personas y no es muy grande (unos 15kg) ideal para una persona de vida activa, le encanta correr y jugar.\r\n\t\r\n\r\n\r\n",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/97ce47b4b1aa1d00a6cc20db905c06f182f76166ff1996b1efec9dd1941f8b0d.jpg",
      "nombre": "MONZA (ACOGIDA)",
      "especie": "Canina",
      "color": "crema",
      "chenil": "B17",
      "peligroso": true,
      "microchip": "NO/941000018459838",
      "cartilla": "NO/ES020200466",
      "rabia": false,
      "fechaRabia": "2017-11-08T00:00:00",
      "esterilizado": true,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "DESP. 22/08/2015\r\nCHIP RABIA PAS EN CMPA \r\n5/2016 cuarentena. tiene hiperqueratosis de la trufa compatible con distemper.\r\n28/06/2016 dhppil\r\n1/07/16 tembleque de 1/3 anterior y cabeza, fallo de propiocepción en EA sobretodo izda.\r\n2/7/16 hvuz. no le observan nada\r\n8/7/2016 sigue con los movimientos involuntarios...\r\n26/09/2016 rabia\r\nregresa de hv 20/12/16 el cuadro nervioso puede ser secuela de moquillo. Le hacen pruebas de filaria por si acaso\r\n9/17 se recoge de guarderia porque tiene epixtasis. Se lleva a hv diagnostican leishmaniosis\r\n6/9/17regresa a cmpa e inicio tto con alopurinol y glucantime, se pospone la revacunación de rabia hasta que se recupere de la leishmania.11/10/17.(seis semanas)\r\nha mejorado mucho. se continua con alopurinol hasta 03/18\r\ndesparasitacion 28/10/17 prazitel y zeronil \r\nvalorar en 1/06/18\r\n",
      "fechaIngreso": "2015-08-22T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": true,
      "horaUrgencias": "21:50",
      "numPolicia": "854(ll) 1087(pr)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "camino Monzalbarba",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 5326,
      "ficha": "05029",
      "raza": "CRUCE DE PITBULL CON DOGO ARGENTINO",
      "sexo": "Macho",
      "fechaNac": "2014-06-22T00:00:00",
      "tamagno": "Grande (26-44 kg)",
      "observaciones": "necesaria licencia y seguro de tenencia de perros potencialmente peligrosos.\r\nFrancisco es sordo pero comprende el lenguaje corporal. Necesita un propietario comprometido con su discapacidad.\r\nLleva mas de dos años con nosotros.   Se merece un hogar ya.\r\nFrancisco actualmente no se encuentra en el centro por lo que si quieres adoptarlo debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/05029 men.jpg",
      "nombre": "Francisco (G)",
      "especie": "Canina",
      "color": "blanco",
      "peligroso": true,
      "microchip": "NO/941000017300339",
      "cartilla": "NO/ES020189736",
      "rabia": false,
      "fechaRabia": "2015-04-29T00:00:00",
      "esterilizado": true,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "el animal parece que es sordo\r\nChip rabia y pas en cmpa zgz \r\n10/5/16 dhppil\r\n14/5/16 sutura en labio ab +aine\r\n31/5/16 quito sutura\r\n2/6/16 rabia\r\n14/11/2016 Llevado a guardería\r\n13/02/19 lesihmania negativo",
      "fechaIngreso": "2015-04-22T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": false,
      "numPolicia": "1660(ll) 1790, 1753(pr)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "avda. Tenor Fleta con García Menendez",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 5875,
      "ficha": "05568",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2012-09-25T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Necesaria Liencia y seguro para la adopción de Pipol\r\n\r\nBueno con la gente.  \r\n\r\nPipol actualmente no se encuentra en el centro por lo que si quieres adoptarlo debes contactar con nosotros en el 976836554.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/05568 Pipol.jpg",
      "nombre": "Pipol (G)",
      "especie": "Canina",
      "color": "marron y blanco",
      "peligroso": true,
      "microchip": "NO/941000018459775",
      "cartilla": "NO/ES02000847",
      "rabia": false,
      "fechaRabia": "2015-11-20T00:00:00",
      "esterilizado": false,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "chip rabia pas en cmpa\r\n14/11/2016 Llevado a guardería.",
      "fechaIngreso": "2015-09-25T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": true,
      "horaUrgencias": "23:55",
      "numPolicia": "812(ll) 1898(pr)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "Prudencio con manifestacion",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 8380,
      "ficha": "08009",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Hembra",
      "fechaNac": "2017-10-23T00:00:00",
      "edad": "Adulto (3 años)",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Es necesaria la obtención de licencia para perro potencialmente peligroso para la adopción de Nora. \r\nInfórmate en 976836554",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/NORA.JPG",
      "nombre": "NORA (GUARDERIA)",
      "especie": "Canina",
      "color": "MARRON",
      "peligroso": true,
      "microchip": "NO/941000022909776",
      "cartilla": "NO/ES020266885",
      "rabia": false,
      "fechaRabia": "2018-06-13T00:00:00",
      "esterilizado": true,
      "perdido": true,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "23/05/2018 se pone pipeta prazitel\r\n31/05/2018 pasa a observación, cuadro gastroentérico. Metronidazol, fortiflora y famotidina\r\n14/06/18 inicio tto coprofloxacino para tos.20mg kg cada 12h\r\noht 12/02/19",
      "fechaIngreso": "2018-05-23T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "horaUrgencias": "00:15",
      "numPolicia": "1228",
      "nombreSolicitante": "POLICIA LOCAL",
      "domicilioSolicitante": "C/ DEMETRIO GALAN BERGUA",
      "disponible": "1",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 7993,
      "ficha": "07624",
      "raza": "CRUCE DE PITBULL",
      "sexo": "Hembra",
      "fechaNac": "2015-11-08T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "peso": "25",
      "observaciones": "necesaria licencia de potencialmente peligroso",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/IMG-20171222-WA0137.jpg",
      "nombre": "Ara(guarderia)",
      "especie": "Canina",
      "color": "Atigrada Marrón",
      "peligroso": true,
      "microchip": "NO/941000021934486",
      "cartilla": "NO/ES020254881",
      "rabia": false,
      "fechaRabia": "2018-02-15T00:00:00",
      "esterilizado": true,
      "perdido": true,
      "evaluacion": "Otro",
      "caracter": "Positivo",
      "observacionesVet": "Recogido por la Nueva Empresa de Recogidas (Centro Canino Aragones), En:\r\nparto reciente, leche en mamas. clamoxil la y deyanil retard. valoro dar galastop\r\nprazitel y zeronil\r\n1/18 esterilizada d.Cea. se toca y se abre la incisión y es reintervenida en HVUZ\r\n26/02/18 dhppi+l\r\nleishmania negativo 02/02/19\r\nguarderia las jaras 21/03/19",
      "fechaIngreso": "2017-11-07T00:00:00",
      "formaEntrada": "Otros",
      "entrada": "Encontrado",
      "numPolicia": "1376",
      "nombreSolicitante": "Policía + (Nueva Empresa de Recogidas)",
      "disponible": "1",
      "tasa": "Ent: Encontrado + Sal:",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 8165,
      "ficha": "07791",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Hembra",
      "fechaNac": "2017-02-08T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/SANSA.jpg",
      "nombre": "SANSA ",
      "especie": "Canina",
      "color": "MARRON Y BLANCO",
      "peligroso": true,
      "microchip": "NO/941000022287872",
      "cartilla": "NO/ES020264116",
      "rabia": true,
      "fechaRabia": "2018-03-22T00:00:00",
      "esterilizado": true,
      "perdido": true,
      "evaluacion": "Apto",
      "caracter": "Otro",
      "observacionesVet": "Muy reactiva. Puede morder!!\r\n02/03/2018 se traslada a guardería para evitar incidentes hasta valoración. \r\n22/03/18 el animal ha mejorado su carácter, Susana ha trabajado con ella y va siendo menos reactiva, aunque seguimos pensando que no es un animal que pueda adoptar cualquiera.\r\n13/02/19 leishmania negativo, ulceras en patas\r\n25/03/19 oht",
      "fechaIngreso": "2018-02-09T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "horaUrgencias": "20:00",
      "numPolicia": "1556 Y 1558   (1093)",
      "nombreSolicitante": "POLICIA LOCAL",
      "domicilioSolicitante": "COMISARIA DE LA PAZ",
      "disponible": "1",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 8243,
      "ficha": "07869",
      "raza": "AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2016-11-27T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/_20180319_121825.jpg",
      "nombre": "LUKI(guarderia)",
      "especie": "Canina",
      "color": "CANELA-BLANCA",
      "peligroso": true,
      "microchip": "941000017742864",
      "cartilla": "ES020265248",
      "rabia": true,
      "fechaRabia": "2018-08-19T00:00:00",
      "esterilizado": true,
      "perdido": false,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "prazitel scalibor. \r\norquidectomia 17/05/18 + amoxi. clav 5 dias\r\n19/08/2018 rabia\r\nguarderia las jaras 21/03/19",
      "fechaIngreso": "2018-03-18T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "horaUrgencias": "15:45",
      "numPolicia": "1701",
      "nombreSolicitante": "POLICIA LOCAL",
      "domicilioSolicitante": "C/ MANIFESTACIÓN Nº 19",
      "disponible": "1",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 6431,
      "ficha": "06104",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Hembra",
      "fechaNac": "2014-11-30T00:00:00",
      "tamagno": "Grande (26-44 kg)",
      "peso": "26",
      "observaciones": "Lula es un cruce de American Staffordshire terrier, raza considerada potencialmente peligrosa, por lo que par adoptarla es necesaria la obtención de licencia de tenencia de perros potencialmente peligrosos.\r\nEs una perrita joven y buena",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/06104.JPG",
      "nombre": "Lula (G)(ACOGIDA)",
      "especie": "Canina",
      "color": "blanco y chocolate",
      "peligroso": true,
      "microchip": "NO/941000019280949",
      "cartilla": "NO/ES020216191",
      "rabia": false,
      "fechaRabia": "2018-08-14T00:00:00",
      "esterilizado": true,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "prazitel, scalibor 6/6/16\r\n08/06/2016 dhppil\r\n21/6/16 rabia\r\n2016 oht hvuz\r\n05/05/2018 DHPPi+L",
      "fechaIngreso": "2016-05-31T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": false,
      "numPolicia": "941(ll) 1212(pr)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "Cuartel de la Paz",
      "disponible": "1",
      "tasa": "Ent: Encontrado",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 7556,
      "ficha": "07212",
      "raza": "CRUCE DE SHAR PEI Y AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2017-01-01T00:00:00",
      "edad": "Adulto (3 años)",
      "tamagno": "Mediano (11-25 kg)",
      "observaciones": "Perrito muy juguetón y obediente. Obedece incluso yendo suelto.",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/0eddf0099dfd04846e24a360ea8862b6aed7acc657031732c576c8cf60066037.jpg",
      "nombre": "VITO CORLEONE (GUARDERIA) ",
      "especie": "Canina",
      "color": "ATIGRADO",
      "chenil": "B25",
      "peligroso": true,
      "microchip": "NO/941000021640353",
      "cartilla": "NO/ES020251565",
      "rabia": false,
      "fechaRabia": "2017-09-01T00:00:00",
      "esterilizado": true,
      "perdido": false,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "El Animal entra Sin Chip, pero le entregan al Operario una Cartilla de Cartulina de Consulta Veterinaria Mundo Liso, con Maxivac Penta del 07/03/2017. Les llama y me dan los datos del Propietario; Onorio Campos, Calle Predicadores nº105, 1 Int, 605157391.\r\n1/9/17 guarderia . \r\n4/18 orquidectomia",
      "fechaIngreso": "2017-07-06T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Otra",
      "urgencias": true,
      "horaUrgencias": "22:10",
      "numPolicia": "974 (Llamada)",
      "nombreSolicitante": "Policía",
      "apellidosSolicitante": "Jorge",
      "telefonoSolicitante": "976245414",
      "domicilioSolicitante": "C/ Ramón Pignatelli, nº76, 1ºC",
      "disponible": "1",
      "tasa": "Ent: Otra + Sal: ",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 8959,
      "ficha": "8579",
      "raza": "MESTIZO",
      "sexo": "Macho",
      "fechaNac": "2017-01-03T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/c3242b92182c5908f14cdfa758d41c1188b76a0585c38851bc16789e2e32c999.jpg",
      "nombre": "TRUFO(ACOGIDA)",
      "especie": "Canina",
      "peligroso": false,
      "microchip": "NO/",
      "cartilla": "NO/",
      "fechaIngreso": "2018-12-22T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "horaUrgencias": "15:50",
      "numPolicia": "1556/1721",
      "disponible": "1",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 9377,
      "ficha": "8974",
      "raza": "COMÚN EUROPEO",
      "sexo": "Hembra",
      "fechaNac": "2019-05-20T00:00:00",
      "tamagno": "Pequeño (< 10 Kg)",
      "peso": "500 GRAMOS",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/Boira 8974.png",
      "nombre": "BOIRA (ACOGIDA)",
      "especie": "Felina",
      "color": "TRICOLOR",
      "peligroso": false,
      "microchip": "NO/941000024074041",
      "cartilla": "NO/AR0016727",
      "perdido": true,
      "fechaIngreso": "2019-06-24T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "numPolicia": "BOTERON",
      "disponible": "1",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    },
    {
      "id": 6481,
      "ficha": "06151",
      "raza": "CRUCE DE AMERICAN STAFFORDSHIRE TERRIER",
      "sexo": "Macho",
      "fechaNac": "2015-01-01T00:00:00",
      "tamagno": "Mediano (11-25 kg)",
      "peso": "18",
      "observaciones": "Me presento, soy Kaos, un perro activo y juguetón, aunque soy muy tímido con los extraños los que me conocen bien saben que una vez que cojo confianza soy muy buen perro.\r\n\r\n\r\nNecesaria licencia y seguro para perro potencialmente peligroso\r\nhttps://www.zaragoza.es/ciudad/IMSP/detalle_Tramite?id=3920\r\n\r\n",
      "foto": "//www.zaragoza.es/cont/paginas/IMSP/mascotas/fb4f50f92edac6bcf1ea8a1d60e2898bc2b98e97ffbbd88d8302b2b6e6bc2512.jpg",
      "nombre": "Kaos (guardería)",
      "especie": "Canina",
      "color": "MARRON",
      "chenil": "B21",
      "peligroso": true,
      "microchip": "NO/941000019020628",
      "cartilla": "NO/ES020216176",
      "rabia": false,
      "fechaRabia": "2018-08-01T00:00:00",
      "esterilizado": true,
      "perdido": false,
      "evaluacion": "Apto",
      "caracter": "Positivo",
      "observacionesVet": "15/6/16 prazitel, scalibor\r\n28/6/16 dhppil\r\n6/7/16 rabia\r\n16/11/16 desp int ext. se envia a guarderia\r\n12/16 Esterilizado CEA\r\n3/17regresa de guarderia por un problema de hongos inicio tratamiento imaverol.\r\n4/17 inicio tratamiento co0n itrafungol ya que el hongo se está extendiendo.\r\n10/5/17 finaliza tratamiento de hongos",
      "fechaIngreso": "2016-06-14T00:00:00",
      "formaEntrada": "Servicio",
      "entrada": "Encontrado",
      "urgencias": false,
      "numPolicia": "1002(ll) 1621(pr)",
      "nombreSolicitante": "Policía Local",
      "domicilioSolicitante": "Fuente de la Junquera 6",
      "disponible": "1",
      "importe": "0.0",
      "bloquear": false,
      "desbloquear": false
    }]


    module.exports = dogList